# Generated by Django 2.0.10 on 2019-02-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20190208_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(null=True, upload_to=None, verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.CharField(max_length=50, verbose_name='장소'),
        ),
    ]
